### ISSUE TITLE
Publicaciones asociadas

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#101]
@marcelorodcla Este podría ser un buen mockup para asociar a las páginas como: Área, Programa, Líneas de Acción, y Principios.
En el caso de Líneas de Acción y Principios no hay "Convocatorias" por lo que no aparecerían.
El botón de "Ver más" nos llevaría a una página (creo que tenemos ya algún diseño para ello, tengo que ver eso) que nos muestre "Todos los eventos de Acción Urbana", etc...

![publicaciones_asociadas](https://cloud.githubusercontent.com/assets/7635775/12616839/6cef8de0-c4e3-11e5-9704-65c8627be7f1.jpg)

**Comment by marcelorodcla** [comment]
Hecho, está con maquetado estático. @jgenso

**Comment by danicotillas** [comment]
Está genial @marcelorodcla 
@jgenso cuando lo hagas dinámico el título también tendrá que serlo:
- Eventos de (Titulo)
- En el blog sobre (Título)
- Convocatorias de (Título)

**Comment by danicotillas** [comment]
No logro ver ningún cambio.
