### ISSUE TITLE
Items en Menús

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#107]
Igual que aparecen Páginas y Enlaces Personalizados sería genial que aparezcan:
- Áreas
- Programas
- Áreas Transversales
- Procesos
- Líneas de Acción.
- Principios
- Servicios
- Páginas
- Enlaces Personalizados

Es decir, todo lo que creamos desde el backend como página dinámica.

![captura de pantalla 2016-01-29 15 21 37](https://cloud.githubusercontent.com/assets/7635775/12685663/1575310e-c69c-11e5-81b2-2877d08d36df.png)

**Comment by jgenso** [comment]
Revisa en el sgte deployment por fa

**Comment by danicotillas** [comment]
Aquí algunos errores @jgenso 
![menus](https://cloud.githubusercontent.com/assets/7635775/12981256/4642f856-d0b6-11e5-9634-2a37fa7e0f84.png)

**Comment by jgenso** [comment]
Revisar en sgte deployment
