### ISSUE TITLE
Widget Categorías / Menú

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#116]
El widget que vemos en el blog con las categorías debe tener resaltado en negro "TODAS" entonces desaparece la opción de "Categorías" que aparece. Sólo queda el título.

Como me comentaste @jgenso sería genial tener la opción de aumentar un menú de selección en los widgets con ese mismo estilo. Ya sea que lo construyes con enlaces o que toma menús por defecto como por ejemplo "Widget Blog", etc..,

![captura de pantalla 2016-02-02 09 56 01](https://cloud.githubusercontent.com/assets/7635775/12751398/52e64b14-c993-11e5-8eb6-6cf98ac612d1.png)

**Comment by jgenso** [comment]
Revisar, sobre los widgets, puedes abrir un ticket nuevo para cada tipo de widget que se te ocurra(no los vamos a hacer ahora) pero tenerlos para no olvidarnos en una sgte fase estaria bien

**Comment by danicotillas** [comment]
Sería bueno contar al menos con el #120 :)
