### ISSUE TITLE
Login - ¿Has olvidado tu contraseña?

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#129]
Sacar "A través de Facebook y Google" y añadir:
¿Has olvidado tu contraseña?
Al pinchar nos lleva a una pantalla dónde hay un campo para poner el email y el texto:

Te enviaremos un enlace a tu correo electrónico para que puedas recuperar tu contraseña:

![captura de pantalla 2016-02-05 09 21 36](https://cloud.githubusercontent.com/assets/7635775/12847496/fa2f0700-cbe9-11e5-9349-6473680cf23e.png)

**Comment by marcelorodcla** [comment]
Listo. revisar en el próximo deploy.

**Comment by danicotillas** [comment]
@marcelorodcla No me aparece todavía el enlace de "¿Has olvidado tu contraseña?"
