### ISSUE TITLE
Email o Password incorrectos

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#130]
Cuando nos equivocamos en el email o el password debe salirnos el mensaje que se ve en la imagen.

![email_incorrecto](https://cloud.githubusercontent.com/assets/7635775/12847696/6df19990-cbeb-11e5-95c4-d7e68ecc9919.jpg)

**Comment by jgenso** [comment]
@marcelorodcla  puedes darle la pinta correcta?, actualmente se ve asi

![captura de pantalla de 2016-02-15 15 56 29](https://cloud.githubusercontent.com/assets/914157/13058893/b91b8c50-d3fc-11e5-9706-81dbbc771822.png)

**Comment by marcelorodcla** [comment]
Listo. revisar en el siguiente commit.
