### ISSUE TITLE
Revisar los permisos para roles de usuario

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#132]
Algunos roles de usuario no se ajustan con los nombres de las partes del menú.
Revisar para que, además, estén en orden.

**Comment by jgenso** [comment]
No entiendo xD

**Comment by danicotillas** [comment]
Esa parte de ahí @jgenso 
![roles_usuario](https://cloud.githubusercontent.com/assets/7635775/12980632/aca77084-d0b3-11e5-8186-9d8cb53c6c47.png)

**Comment by natalynanda** [comment]
@danicotillas please review
