### ISSUE TITLE
Botones Anterior/Siguiente en EVENTOS

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#134]
Siguiente - Anterior se debería quedar flotante para ver mejor dónde está y poder pinchar.
El fondo podría ser un blanco al 50% para que se note que está por encima pero que siguen cosas debajo.
http://staging.martadero.org/backend/events/add/new#
![siguiente_anterior](https://cloud.githubusercontent.com/assets/7635775/12850863/5f87eb7c-cbfd-11e5-897b-184b050b6ee3.jpg)

**Comment by marcelorodcla** [comment]
hecho. revisar en el siguiente commit.

**Comment by danicotillas** [comment]
@marcelorodcla Si puedes subir los que has hecho hasta ahora, como éste que es importante ver cómo queda, lo chequeo al tiro.

**Comment by danicotillas** [comment]
@marcelorodcla si, no nos hemos entendido. Lo charlé con @jgenso para explicar cómo yo lo veía y realmente puede ser más complejo de hacer. Igual testee con dos compañeros y quedamos en una opción simple. Que estén arriba y abajo y diferenciados por el color gris #555555 . De esa forma es más sencillo y se ve rápido.
Te paso unos screenshots:

Para la parte de arriba
![anterior_siguiente_1](https://cloud.githubusercontent.com/assets/7635775/13177994/fa990182-d6f2-11e5-9319-a927088064b6.jpg)

Para el footer
![anterior_siguiente_2](https://cloud.githubusercontent.com/assets/7635775/13177995/fa9c40d6-d6f2-11e5-9912-66f3869881b5.jpg)

**Comment by marcelorodcla** [comment]
hecho revisar en el próximo commit
