### ISSUE TITLE
Correo ele"´"ctronico

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#135]
Hay un error con una tilde en "Correo electrónico" en todo lado. Está sobre la c y tiene que estar sobre la o.

Además esta es una captura de "Redes" y al no existir el campo "Correo electrónico" pilla la fecha.
![captura de pantalla 2016-02-05 12 25 28](https://cloud.githubusercontent.com/assets/7635775/12852094/ac16aa18-cc03-11e5-84f5-40a9ebe1482c.png)

**Comment by jgenso** [comment]
Revisar en el sgte deploy
