### ISSUE TITLE
Servicios: UPIs y UPAs

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#142]
Hay que crear en el Backend dentro de servicios la opción de:
- UPI
- UPA

para seleccionar uno de los dos.

Dependiendo del que elijas debe colocarse en el frontend según el diseño de abajo:

![servicios_upis_upas](https://cloud.githubusercontent.com/assets/7635775/12982281/81b31aac-d0ba-11e5-95ba-1609a9a0afc3.jpg)

**Comment by jgenso** [comment]
@danicotillas probar en el sgte deployment, ojo tienes que entrar al backend y asginarle el tipo correspondiente a cada servicio
