### ISSUE TITLE
Vista detalle de SALAS

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#146]
Pensé que ya teníamos diseñada esta pantalla... pero parece que no. @marcelorodcla si acaso ya la tenías me avisas, sino aquí el mockup para poder diseñarla.

![salas](https://cloud.githubusercontent.com/assets/7635775/13058718/6576f086-d3fb-11e5-9994-0b8b11fcc7e7.jpg)

**Comment by marcelorodcla** [comment]
@jgenso Template hecho, esta en el archivo espacio.html.
