### ISSUE TITLE
Estilos de enlace

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#148]
En h4, h3, h2 hacer que el estilo de enlace sea igualmente en naranja con underline.

**Comment by marcelorodcla** [comment]
Listo, no se puede poner underline porque la tipografia no soporta, la linea se sobre pone al texto. También tuve que cambiar el borde del circulo que contiene la fecha. revisar en el siguiente commit.

**Comment by danicotillas** [comment]
@marcelorodcla es sólo cuando es enlace, no siempre.
Me he dado cuenta viendo http://staging.martadero.org/blog/

**Comment by marcelorodcla** [comment]
Lo siento, ya está corregido.

**Comment by danicotillas** [comment]
Mil gracias @marcelorodcla ¿Puedes subirlo porfa para ver los cambios?

**Comment by danicotillas** [comment]
Argh... me estoy haciendo yo sólo un lío con los estilos @marcelorodcla 
¿Puedes decirme sobre qué archivo lo estás modificando y las líneas para hacer yo las pruebas locales?
Prefiero equivocarme yo y probar.

**Comment by natalynanda** [comment]
@danicotillas  los estilos ya estan? tengo que aniadirlo a todo el sistema? o cual es mi tarea aqui?

**Comment by danicotillas** [comment]
@natalynanda Los estilos ya están pero hay que corregir algunas cosas. El problema es que es en less y no sé cómo se modifica. Deja este tickets abierto para cuando nos veamos algún día y lo vemos en directo. Gracias.
