### ISSUE TITLE
Visualización de PRINCIPIOS

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#153]
Aquí la pantalla como se podrían ver cada PRINCIPIO.

![principios](https://cloud.githubusercontent.com/assets/7635775/13080629/e89d25a8-d49f-11e5-876a-56db5eb728c2.jpg)

**Comment by marcelorodcla** [comment]
@danicotillas  por favor llenar un principio, actualmente me lleva a 404

**Comment by danicotillas** [comment]
Si, aún falta que lo habilite @jgenso
