### ISSUE TITLE
Propuesta para DASHBOARD

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#162]
![dashboard](https://cloud.githubusercontent.com/assets/7635775/13112213/3f0785da-d560-11e5-8f7f-65f775327dc5.jpg)

**Comment by natalynanda** [comment]
@danicotillas  esto es en la pantalla de administracion digital verdad?

Necesito mas informacion.
Existe una seccion que dice, he leido y entendido la informacion sobre las solicitudes... 
cual es el evento del checkbox? solo mostrar mientras no se haya tickeado, Cuando se tickeo ya no debe mostrar este sector de la informacion? O cual es la idea?

**Comment by danicotillas** [comment]
Es la pantalla que sale en Dashboard, a la que te tiene que llevar nada más te loguees.
La idea es que si no haces click el botón de "Hacer una solicitud" no se activa.

La gente es así...
