### ISSUE TITLE
Error en la subida de imágenes

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#169]
Si subimos una imagen que tiene en el nombre espacio o mayúsculas aparece en el previsualizador pero al guardar desaparece.

**Comment by natalynanda** [comment]
@danicotillas esto es al crear una solicitud de un evento? http://staging.martadero.org/backend/events/pendingevents

**Comment by danicotillas** [comment]
@natalynanda  Ahora no recuerdo dónde, imagino que en todo lado.

**Comment by natalynanda** [comment]
No se puede reproducir el bug, lo revisamos con @danicotillas decidio cerrarlo.
