### ISSUE TITLE
Recover Password no existe

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#173]
Este link no existe: http://staging.martadero.org/recover/password
Además pone "¿Haz...?" tiene que poner **¿Has**

**Comment by natalynanda** [comment]
@danicotillas hice un recovery en el ticket #143  se trata de lo mismo?

**Comment by danicotillas** [comment]
@natalynanda  Si

**Comment by hdwilber** [comment]
I have been running and playing with it, and it works. Perhaps, We need more information about this issue.
PS. Some misspelling were fixed. But, it does not close this issue.

**Comment by hdwilber** [comment]
@jgenso . Password recovering is working, Do you think, We could close this issue?
