### ISSUE TITLE
Problemas de visualización en Linux

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#190]
@jgenso el Juan está intentando subir los equipos pero sigue con este problema grave de visualización en su compu. No puedo tomar capturas de pantalla, tal vez es el navegador, pero hemos probado otros y nada. Tiene pinta ser el S.O. Me dices cómo crees mejor hacer.

**Comment by danicotillas** [comment]
¿Sabes por qué puede ser esto o aún no?

**Comment by hdwilber** [comment]
Could you give me more information about this issue?. I do not have visualization problems, here.

**Comment by jgenso** [comment]
Try diferent screen size also diferent browsers(firefox, chrome)
