### ISSUE TITLE
Portada

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#2]
Probando me he dado cuenta que cuando pinchas en el menú de la izquierda, si estás navegando, te olvidas de donde era que habías pinchado. Tal vez se pueda poner un hover de color (naranja) y que cuando pinches se mantenga tanto el color como el nombre abierto igual en color.
![captura de pantalla 2015-06-25 16 44 47](https://cloud.githubusercontent.com/assets/7635775/8365203/92a763d4-1b59-11e5-98a4-3143329004d8.png)

El menú superior mejor que muestre el submenú al hacer hover.
Para la pestaña de "Categorías" creo que no se entiende y está muy suelto. ¿Si lo ponemos como en la imagen?
¿A ustedes el "/" antes de cada palabra les hace ruido? No sé si sería mejor darle un poco de espacio entre cada una y listo.
![captura-de-pantalla-2015-06-25-16 55 56](https://cloud.githubusercontent.com/assets/7635775/8365615/45b4912a-1b5c-11e5-9c90-b268bb16b5e6.jpg)

Luego, algo que quiero discutir con ustedes es cómo hacer para que haya Actividades y Talleres mezclado en la página de inicio pero que se pueda filtrar de alguna forma.

**Comment by jgenso** [comment]
"Todo" es un evento, osea un taller, un evento, una actividad, una estadia, por lo que pueden aparecer en una lista de "eventos" y ser filtrados por su subtipo

**Comment by danicotillas** [comment]
Perfecto! Veremos de ponerlo desde la parte de "Filtrar".
- Eventos.
- Talleres.
- Residencias.
- / -
- Artes Escénicas.
- Artes Visuales.
  ....

**Comment by danicotillas** [comment]
![index](https://cloud.githubusercontent.com/assets/7635775/9593032/d6d0b90a-5017-11e5-9aea-3ba263885c27.png)
