### ISSUE TITLE
"Cargando" en creación de nuevo evento

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#211]
Cuando se crea un nuevo evento tarda mucho en cargar las salas... normal!
Para ello tal vez en esta pantalla (http://staging.martadero.org/backend/events/add/new) podría aparecer un mensaje que diga "Cargando" o la típica ruedita que hace las veces de mensaje de cargando.

**Comment by hdwilber** [comment]
I think it is the same than issue #175
