### ISSUE TITLE
Nuevo post

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#30]
Al subir un nuevo post la parte del calendario se ve desconfigurado.
La parte de etiquetas no se entiende muy bien, además que no se visibilizan luego.
La parte de categorías debería haber un campo para poner "otras categorías" para los admins.

![captura de pantalla 2015-12-16 18 04 39](https://cloud.githubusercontent.com/assets/7635775/11855374/3cc58004-a420-11e5-8c3f-ef86c5da7ddc.png)

**Comment by jgenso** [comment]
Al subir un nuevo post la parte del calendario se ve desconfigurado. -- resuelto
La parte de etiquetas no se entiende muy bien, además que no se visibilizan luego. -- en progreso
La parte de categorías debería haber un campo para poner "otras categorías" para los admins.  -- no aplica si los admins quieren crear nueva categoria que lo hagan mediante el crud correspondiente

**Comment by danicotillas** [comment]
Explícame qué es un crud porfa para entenderlo mejor. El resto perfecto, quedo a la espera de las etiquetas.

**Comment by jgenso** [comment]
Me refiero a que ya se tiene un modulo para crear categorias, ponerlo aqui es redundante

**Comment by jgenso** [comment]
Revisar en el sgte deployment
