### ISSUE TITLE
Enriquecedor de texto

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#42]
Creo que sería ideal quitar los botones que he tachado. Al tener tanta opción la gente se suele volver loca. Veamos qué otras opciones tiene como me decías.

![enriquecedor-de-texto](https://cloud.githubusercontent.com/assets/7635775/11965537/7f5c8d36-a8cb-11e5-8837-fb9ab0dc2788.jpg)

**Comment by jgenso** [comment]
revisar
