### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#43]
El logo se queda sólo en el menú negro y cuando se hace scroll-down el menú negro queda fijo.
Habría que hacer de un gris más claro el texto del menú tipo #999.

![captura de pantalla 2015-12-16 18 08 13](https://cloud.githubusercontent.com/assets/7635775/11855420/862d6ab8-a420-11e5-980d-d7fdfae78342.png)

**Comment by marcelorodcla** [comment]
hecho, revisar en el próximo deploy

**Comment by danicotillas** [comment]
@marcelorodcla  Ok, ver #79 con algunos problemas que hay
