### ISSUE TITLE
Calendario

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#46]
Se ve siempre mal:

![captura de pantalla 2015-12-22 17 39 26](https://cloud.githubusercontent.com/assets/7635775/11966578/09d08830-a8d3-11e5-91fd-5dfdd01760a1.png)

**Comment by marcelorodcla** [comment]
No está agarrando las hojas de estilo correctas

**Comment by jgenso** [comment]
revisar

**Comment by danicotillas** [comment]
Lo he revisado en 2 partes y está perfecto.
Ahora, todo lo que tiene que ver con fechas se ve en inglés. Además cuando eliges fecha el primer día que aparece es SUN (Domingo) y eso va a generar confusión. Ver de poner en español porfa.
