### ISSUE TITLE
Imagen SUSCRIBETE BOLETIN

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#47]
En lugar de poner un campo para poner el email y suscribirse, vamos a poner una imagen con link a: http://martadero.org/listas/?p=subscribe&id=1

La imagen es la siguiente
![suscribete_boletin](https://cloud.githubusercontent.com/assets/7635775/11965895/4585d060-a8ce-11e5-8000-913e3e824804.jpg)

Para el footer crearé otra.

**Comment by danicotillas** [comment]
@jgenso Imagen para el footer
![suscribete_boletin_footer](https://cloud.githubusercontent.com/assets/7635775/12173124/628045a6-b52b-11e5-8092-c84b4282742c.png)

**Comment by marcelorodcla** [comment]
Hecho,  revisar en el siguiente deploy.

**Comment by danicotillas** [comment]
Faltaría poner la imagen en el menú right (como en http://staging.martadero.org/blog/) y poner el link a http://martadero.org/listas/?p=subscribe&id=1
