### ISSUE TITLE
http://staging.martadero.org/backend/users/add/new

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#5]
Nombre
Nombre de usuario
Contraseña
Rol [a los usuarios les viene por defecto. Sólo Super Admin y Admin puede cambiar el rol]
Correo electrónico
Zona horaria
Idioma
Links a redes (+ info sobre Barrio Hacker [link] )
· charlemos.barriohacker.net/
· redlibre.barriohacker.net/
· lamochila.barriohacker.net
· comoes.barriohacker.net
· facebook.com/
· twitter.com/
· youtube.com/
· Otros [sumar otros links hasta donde quiera]
Bio
Verificado ¿qué es esto?

**Comment by jgenso** [comment]
Verificado implica que ha validado su cuenta(email)
