### ISSUE TITLE
Settings/profile

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#52]
La edición del perfil de usuario se ve así:

![captura de pantalla 2016-01-07 10 16 11](https://cloud.githubusercontent.com/assets/7635775/12172524/cc620990-b527-11e5-8b93-e4faa18a6237.png)

**Comment by marcelorodcla** [comment]
Listo. Revisar en el siguiente delploy

**Comment by danicotillas** [comment]
Perfecto, aunque se ha perdido el menú Dashboard de la izquierda.

**Comment by marcelorodcla** [comment]
Listo, revisar en el siguiente deploy
