### ISSUE TITLE
Dashboard/Perfil

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#53]
Si desde el dashboard, pinchamos en "Perfil" se pierde el menú de administración.

![captura de pantalla 2016-01-07 10 20 36](https://cloud.githubusercontent.com/assets/7635775/12172601/53a6819c-b528-11e5-9716-ef0e42338776.png)

**Comment by marcelorodcla** [comment]
Hecho. Revisar el en siguiente deploy.
