### ISSUE TITLE
Menú admin dashboard

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#54]
Cuando pinchas en uno de los items que despliegan submenú (por ej. "Organización" en la imagen) los subitems tienen que tener un poco de espacio a la izquierda para que no se confunda con el anterior. O tener unos puntos o líneas que visualmente haga que sepa dónde estás.

Cambiar "Módulo Blog" por "Blog".

![captura de pantalla 2016-01-07 10 21 33](https://cloud.githubusercontent.com/assets/7635775/12172626/76d58fb4-b528-11e5-810b-db15bc70ae35.png)

**Comment by marcelorodcla** [comment]
Listo. Revisar en el siguiente deploy.
