### ISSUE TITLE
Fechas en español

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#55]
Pongo esta captura como ejemplo pero en realidad está en todo lado.
Dice "Fecha: December 16, 2015" y debería decir "Fecha: 16 de diciembre de 2015".
Para eventos y talleres tendrá que decir además el día de la semana: lunes, martes, miércoles... así que tal vez tenga que estar igual en todo lado.

![captura de pantalla 2016-01-07 10 25 53](https://cloud.githubusercontent.com/assets/7635775/12172737/12a237ee-b529-11e5-8170-a15fbbc21cec.png)

**Comment by jgenso** [comment]
revisar en el sgte deployment
