### ISSUE TITLE
Pantalla BLOG principal

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#56]
Poner los enlaces a categorías (Temas) y etiquetas... Todos ellos son enlaces.

![blog_principal](https://cloud.githubusercontent.com/assets/7635775/12206151/a7aba950-b615-11e5-8b51-1cc9661649c7.jpg)

@jgenso Acabo de ver que el problema de la imagen es por esto: lo sube como src="file**/preview/**...." Tiene que desaparecer el **/preview/** para que se vea bien.

![captura de pantalla 2016-01-26 12 29 10](https://cloud.githubusercontent.com/assets/7635775/12586909/7d202c62-c428-11e5-9549-b79c70a44f3f.png)

**Comment by danicotillas** [comment]
Aquí la visualización del detalle en el post aunque se podría ver de poner algún símbolo de fontawesome como en el siguiente ejemplo:
![blog_detalle](https://cloud.githubusercontent.com/assets/7635775/12206295/7d01401a-b616-11e5-862f-e0688c0c72c3.jpg)

Los icons son "tag" y "tags":

![blog_detalle_2](https://cloud.githubusercontent.com/assets/7635775/12206406/1d421f36-b617-11e5-97a9-22dbd00319b7.jpg)

**Comment by marcelorodcla** [comment]
Los iconos ya están puesto, pero no está llamando a la categorías y etiquetas
