### ISSUE TITLE
Pantalla RESULTADOS DE BÚSQUEDA

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#61]
![resultados busquetas](https://cloud.githubusercontent.com/assets/7635775/12206865/bf06d40e-b619-11e5-89eb-9a3f240e78d5.jpg)

**Comment by jgenso** [comment]
Marcelo puedes darle una revisada para ver si esto ya esta con html?

**Comment by marcelorodcla** [comment]
Ya está en el sistema, falta agregarle funcionalidad.
