### ISSUE TITLE
Mapa MENU Header

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#65]
- QUIÉNES SOMOS
  - Equipo Humano
  - Conexiones
- ÁREAS
  - Artes Visuales
  - Audiovisual
  - Artes Escénicas
  - Música
  - Arquitectura y Patrimonio
  - Interacción Social
- PROGRAMAS
  - Formarte
  - Creatividad Infantil
  - Acción Urbana
  - Vivo y Verde
  - VEAC
  - Polit. Cult. y Redes
  - prAna
- PRINCIPIOS
  - Innovación
  - Investigación
  - Experimentación
  - Rigor conceptual y formal
  - Integración
  - Intercambio de conocimientos y experiencias
  - Interculturalidad
- LÍNEAS DE ACCIÓN
  - Desarrollo Barrial
  - Conectividad de Redes
  - Incidencia
  - Cultura Libre
  - Inter-Media-Acción
  - Autogestión
- CONEXIONES
  - Red 4C
  - Telartes
  - JUNTXS
  - R_en_R
  - Eje Centr4l
  - REDesearte Paz
  - Centros del Sur
  - Bice Bugatti
  - Viva América
  - Mataderos
  - Rehabilitación de Barrios
- CORRESPONSABILIDAD
  - Fondo para el Desarrollo de las Artes - FONDART
  - Apoyos
- CONTACTO
  - Dónde estamos
  - Ser parte del equipo
  - Hazte amig@ del mARTadero

**Comment by jgenso** [comment]
Marcelo Areas y programas tienen 3 niveles puedes ver que funcione?(Ya se genera desde scala), como en otros proyectos cuando pasas el mouse sobre el item despliega un nuevo submenu(3er nivel)

**Comment by danicotillas** [comment]
@jgenso @marcelorodcla  el menú debe abrirse al hacer mouse-over no al clickar.

**Comment by marcelorodcla** [comment]
Habilitado para abrir al pasar encima y para tres niveles.

**Comment by danicotillas** [comment]
@marcelorodcla @jgenso Habría que poner los items que aparecen arriba. Imagino que hasta que exista la posibilidad de crearlo desde el backend. De momento que aparezcan los items que se ven y vamos creando las páginas.
