### ISSUE TITLE
Incluir botones de compartir via addthis

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#71]
@jgenso @marcelorodcla Les paso aquí los códigos ser incluidos en cada parte de la web: páginas, entradas, eventos, etc... para que la gente pueda compartir.
Están con addthis, no deberían necesitar los códigos de acceso pero caso que sí me dicen.

Copy and paste the following code before the </body> tag in the HTML of your website on every page you want AddThis to work.

```
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=martadero" async="async"></script>
```

Code for Activated Tools
Some of the tools you have activated need additional code to show within the body of your page. Copy and paste the corresponding code where you want the tools to show.

```
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<div class="addthis_sharing_toolbox"></div>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=martadero" async="async"></script>
<script type="text/javascript">
var addthis_share = addthis_share || {}
addthis_share = {
    passthrough : {
        twitter: {
            via: "martadero"
        }
    }
}
</script>
```

**Comment by marcelorodcla** [comment]
hecho
