### ISSUE TITLE
Mover items en backend

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#72]
@jgenso ¿Hay alguna posibilidad que los items que se ven en la imagen se puedan mover para colocarlos en el orden deseado con un drag&drop? No solamente en áreas, sería ideal casi para todos los items: servicios, equipos, programas,... Estoy viendo que va a ser necesario ordenar todo.
Si no drag&drop por lo menos una flecha de subir y bajar, algo sencillo.

![captura de pantalla 2016-01-13 19 20 40](https://cloud.githubusercontent.com/assets/7635775/12311063/09175716-ba2b-11e5-9a9d-7f6fde8e3dd1.png)

**Comment by danicotillas** [comment]
Hacer que se vea un puntero y los menúes se actualicen según el orden del backend.

**Comment by jgenso** [comment]
@marcelorodcla todas las tablas que se puedan ordenar agregarles una clase, y agregar el efecto de puntero que se menciona

**Comment by marcelorodcla** [comment]
hecho, revisar, se subirá en el próximo push
