### ISSUE TITLE
Permitir incluir clases en Widgets

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#78]
No está dejando incluir código con clases personalizadas en el HTML de los widgets, por eso se ve desconfigurado, por ejemplo aquí: http://staging.martadero.org/pagina/bibliolibre

![staging martadero org backend widgets edit 56991b85e4b0e8ca5c9350bd](https://cloud.githubusercontent.com/assets/7635775/12366307/a416b60e-bbb0-11e5-9ac3-1b0a64de0bff.png)

**Comment by jgenso** [comment]
Acabo de verificar funciona con clases
