### ISSUE TITLE
Arreglos CSS 18 enero 2015

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#79]
En el Administrador el menú blanco queda oculto por el negro.
![captura de pantalla 2016-01-18 10 58 47](https://cloud.githubusercontent.com/assets/7635775/12394481/8892a298-bdd2-11e5-8afe-26e5e1f66098.png)

El menú de Administrador se me muestra así, uso Chrome.
![captura de pantalla 2016-01-18 11 00 05](https://cloud.githubusercontent.com/assets/7635775/12394497/a53811a8-bdd2-11e5-9050-c4de7c77a7df.png)

Los sub-submenus de Procesos aparecen en blanco. Además tienen que estar en horizontal con el área a la que pertenecen. Estoy viendo justo ahora que en "Quienes Somos" se ve bien...
![captura de pantalla 2016-01-18 a las 11 00 47](https://cloud.githubusercontent.com/assets/7635775/12394531/dfbf2c6c-bdd2-11e5-87ac-1129b8361b97.png)

**Comment by danicotillas** [comment]
@marcelorodcla Atento también a cómo se ve la página de http://staging.martadero.org/convocatorias ahora que he subido más convocatorias.

**Comment by danicotillas** [comment]
@marcelorodcla Pasa lo mismo en http://staging.martadero.org/servicios Imagino que solucionando uno se solucionan todos.

**Comment by danicotillas** [comment]
En .fa de font-awesome.min.css:4 colocar margin-right: 10px;

![captura de pantalla 2016-01-30 17 08 50](https://cloud.githubusercontent.com/assets/7635775/12698497/2fe302c2-c774-11e5-9581-796136c7c042.png)

**Comment by danicotillas** [comment]
Colocar estos valores de CSS para que la D de "Destacado" quede centrada
![captura de pantalla 2016-01-30 17 20 56](https://cloud.githubusercontent.com/assets/7635775/12698554/e86236c8-c775-11e5-9a40-dc5dd1388e4a.png)

**Comment by danicotillas** [comment]
![captura de pantalla 2016-01-30 16 53 51](https://cloud.githubusercontent.com/assets/7635775/12698707/237b4a2a-c77a-11e5-8406-07f0ac69e63e.png)

**Comment by marcelorodcla** [comment]
Revisar
