### ISSUE TITLE
Reubicación botón "Nuevo"

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#84]
@marcelorodcla Estoy ya probando con el equipo la nueva web y en particular con esto nadie encuentra el botón "nuevo" en las páginas interiores. ¿Se podría mover al lado del título de la página? Gracias
![boton_nuevo](https://cloud.githubusercontent.com/assets/7635775/12483859/a8994198-c02d-11e5-93d7-3f6857cac714.jpg)

**Comment by marcelorodcla** [comment]
Listo, se subira en el siguiente push
