### ISSUE TITLE
Inclusión "bullet" en páginas

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#94]
Que en las páginas creadas como http://staging.martadero.org/pagina/mediateca aparezca el bullet de la imagen al lado del título. Ah! y de paso centrarlo con el texto porfa.

![captura de pantalla 2016-01-25 11 20 52](https://cloud.githubusercontent.com/assets/7635775/12555081/ce261bea-c355-11e5-9536-b27e6730033e.png)

**Comment by danicotillas** [comment]
Centrar el bullet con el texto. A mí me sale que tendría que ser top: -2px; en .glyphicon del bootstrap.min.css:5
![captura de pantalla 2016-01-30 16 53 51](https://cloud.githubusercontent.com/assets/7635775/12698418/1e053298-c772-11e5-9c50-169ffd8b23fa.png)

**Comment by marcelorodcla** [comment]
hecho, verificar en el siguiente push
