### ISSUE TITLE
Corrección texto en headers

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#95]
@marcelorodcla Si te fijas cuando haces scroll down el texto del menú blanco aparece encima del menú negro. 
![captura de pantalla 2016-01-25 18 01 53](https://cloud.githubusercontent.com/assets/7635775/12566004/cc156d8c-c38d-11e5-8adf-f4b8514d29ef.png)

**Comment by marcelorodcla** [comment]
hecho
