### ISSUE TITLE
CSS main.content de todas las páginas

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#96]
Colocar en todas las páginas como se muestra en la imagen, que es la misma estructura que en BLOG.
@jgenso aún queda ver si tenemos posibilidad de crear templates que se elijan cuando creas una página.

![captura de pantalla 2016-01-26 12 25 09](https://cloud.githubusercontent.com/assets/7635775/12586775/ff4f8a58-c427-11e5-82fe-8e8b0aea7431.png)

**Comment by marcelorodcla** [comment]
cambiada distribución a 8 - 4. Revisar en el siguiente push
